---
- hosts: staging
  become: true
  roles:
    - role: base

# =========================
- hosts: staging
  roles:
    - role: weight_tracker

# =========================
- hosts: staging
  roles:
    - role: envfile

# =========================
- hosts: staging
  become: true
  roles:
    - role: services
