# ================= Staging =================
---
- hosts: staging
  become: true
  roles:
    - role: base

# =========================
- hosts: staging
  roles:
    - role: weight_tracker

# =========================
- hosts: staging
  roles:
    - role: envfile

# =========================
- hosts: staging
  become: true
  roles:
    - role: services
# ================= production =================
---
- hosts: production
  become: true
  roles:
    - role: base

# =========================
- hosts: production
  roles:
    - role: weight_tracker

# =========================
- hosts: production
  roles:
    - role: envfile

# =========================
- hosts: production
  become: true
  roles:
    - role: services