- name: Creating an empty file
  file:
    path: /etc/systemd/system/myapp.service
    state: touch

- name: generate service file from template
  template:
    dest: /etc/systemd/system/myapp.service
    src: roles/services/templates/myapp.j2

- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable service httpd and ensure it is not masked
  ansible.builtin.systemd:
    name: myapp.service
    enabled: yes
    masked: no

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    name: myapp.service  
    state: started