- name: clone main branch from bootcamp app
  ansible.builtin.git:
    repo: https://github.com/MatanTal2/bootcamp-app.git
    dest: /home/{{ ansible_user_id }}/bootcamp/
    clone: yes
    update: yes
    force: yes
- name: the installation location 
  ansible.builtin.debug:
    msg: /home/{{ ansible_user_id }}/bootcamp/

# install hapi 
- name: install dependencies
  command: "npm install {{ item }}"
  args:
    chdir: /home/{{ ansible_user_id }}/bootcamp
  with_items:
    - '@hapi/hapi@19'
    - '@hapi/bell@12' 
    - '@hapi/boom@9'
    - '@hapi/cookie@11' 
    - '@hapi/inert@6'
    - '@hapi/joi@17' 
    - '@hapi/vision@6' 
    - 'dotenv@8'
    - 'ejs@3' 
    - 'postgres@1'

# - name: npm aduit fix
#   command: "npm aduit fix"
#   args:
#     chdir: /home/{{ ansible_user_id }}/bootcamp

- name: install nodemon
  command: "npm install --save-dev nodemon@2"
  args:
        chdir: /home/{{ ansible_user_id }}/bootcamp

# - name: npm aduit fix
#   command: "npm aduit fix"
#   args:
#     chdir: /home/{{ ansible_user_id }}/bootcamp


- name: npm init -y
  command: "npm init -y"
  args:
    chdir: /home/{{ ansible_user_id }}/bootcamp
